### ISSUE TITLE
Licence manquante

### ISSUE THREAD

**Issue by jgribonvald** [EsupPortail/esup-sygal-import-ws#1]
Merci d'ajouter la licence à ce projet - tout projet publique doit en avoir une, et de préférence Apache 2.0 ou compatible.

**Comment by bertrandgauthier** [comment]
Bonjour. Il y a bien un fichier LICENSE.

**Comment by jgribonvald** [comment]
Bonjour toutes mes excuses, effectivement.
Par contre github ne la détecte pas, et quid de la compatibilité avec la licence apache ?
D'autre part il serait bien que les tous les fichiers codes source aient en header les éléments de licence.

**Comment by bertrandgauthier** [comment]
http://www.cecill.info/licences.fr.html
Peut-être pourrions-nous passer à la CeCILL-B mais ce n'est pas de mon ressort.

**Comment by jgribonvald** [comment]
Je pense que ce serait déjà une bonne chose. Merci

**Comment by bertrandgauthier** [comment]
On ne changera pas de licence pour l'instant.
http://www.cecill.info/faq.fr.html#pourquoi-cecill
Mais au fait, quels arguments plaident en faveur de la licence Apache 2.0 ?

**Comment by jgribonvald** [comment]
Pour la partage au sein de la [communauté Apereo](https://www.apereo.org/licensing) , et même [ESUP ](https://www.esup-portail.org/wiki/pages/viewpage.action?pageId=400818195)le recommande.

La grosse différence est que la licence apache permet à tout un chacun de réutiliser/modifier/distribuer tout ou partie du code source.
On peut trouver des articles sur le sujet, et on peut trouver des articles sur des problèmes de distribution de solutions sous une licence GNU.

Le gros point noir est que tout ce qui est GNU ne permet pas d'être réutilisé dans un quelconque projet sans en contaminer le projet. Aussi un projet apache ne peut intégrer une dépendance sous GNU, l'inverse est aussi valable. 

Après je ne suis pas avocat, si je fais erreur il faut me le dire !

**Comment by prigaux** [comment]
Euh, les projets GNU sont soit en GPLv3+ ou en LGPLv3+. Ces deux licences sont compatibles avec Apache v2 !

**Comment by jgribonvald** [comment]
Alors voici un lien qui indique la compatibilité entre [licences GPL et apache](http://www.apache.org/licenses/GPL-compatibility.html), GPLv3 uniquement peut intégrer des librairies apache, mais l'inverse n'est pas possible, il semble que ce soit la même chose avec LGPL.
Aussi voici la liste des [licences compatibles](https://apache.org/legal/resolved.html#what-can-we-not-include-in-an-asf-project-category-x) avec un projet apache.
